### ISSUE TITLE
Prefill accepted meetings in time tracking

### ISSUE THREAD

**Issue by tomheller** [ffriedl89/timetracking#8]
* [ ] login with outlook calendar (centrify) 
* [ ] Get meeting timeslots to prefill entries
* [ ] Automatically add accepted meetings
* [ ] Propose entries for tentatively accepted meetings

**Comment by tomheller** [comment]
Office365 calendar API
https://msdn.microsoft.com/en-us/office/office365/api/calendar-rest-operations#GetEvents

**Comment by tomheller** [comment]
We also need a way to disable this for vacation days.
